apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: kube-ops
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: grafana
    spec:
      selector:
        matchLabels:
          k8s-app: grafana
      containers:
      - name: grafana
        image: grafana/grafana:7.4.3
        ports:
        - containerPort: 3000
          protocol: TCP
#        volumeMounts:
#        - mountPath: /var
#          name: grafana
#          subPath: grafana/data
#        - mountPath: /ssl
#          name: ssl
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: INFLUXDB_HOST
          value: influxdb.kube-system
        - name: GF_SERVER_HTTP_PORT
          value: "3000"
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "false"
        - name: GF_SERVER_ROOT_URL
          value: /
        - name: GF_SMTP_ENABLED
          value: "true"
        - name: GF_ALERTING_ENABLED
          value: "true"
        - name: GF_ALERTING_EXECUTE_ALERTS
          value: "true"
        readinessProbe:
          httpGet:
            path: /login
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 2
#      volumes:
#      - name: ssl
#        secret:
#          secretName: ssl
#      - name: grafana
#        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: grafana
  name: grafana
  namespace: kube-ops
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      nodePort: 32223
  selector:
    k8s-app: grafana
